33 define the quiz data model
DIT113-V22/group-01 pull request #52
Opened 2022-04-29 21:50 UTC by plepisnew

Closes #33 

Created Models for Question, Category, UserAnswer and QuizState.
Encapsulated fields for each Model. Added Helper methods that will be necessary in the UI.

2022-04-29 22:12 UTC, platisd commented
Why is `33` in the title?
That is an unconventional way of referring to issues.

2022-04-30 11:08 UTC, plepisnew commented
> Why is `33` in the title? That is an unconventional way of referring to issues.

Should I also refer to the issue in the title, using `#33` ?

2022-04-30 11:39 UTC, Lancear commented
> > Why is `33` in the title? That is an unconventional way of referring to issues.
> 
> Should I also refer to the issue in the title, using `#33` ? I just assumed we only have to refer to it in the description.

I think you can simply remove the 33 from the title since its in the description already
![image](https://user-images.githubusercontent.com/52662014/166103974-6fef45e0-0a6d-4f14-a54d-7db2599268f0.png)

2022-04-30 11:44 UTC, plepisnew commented
> > > Why is `33` in the title? That is an unconventional way of referring to issues.
> > 
> > 
> > Should I also refer to the issue in the title, using `#33` ? I just assumed we only have to refer to it in the description.
> 
> I think you can simply remove the 33 from the title since its in the description already ![image](https://user-images.githubusercontent.com/52662014/166103974-6fef45e0-0a6d-4f14-a54d-7db2599268f0.png)

will do! thanks

2022-04-30 13:11 UTC, platisd commented
What @Lancear said 👍

2022-04-30 14:39 UTC, JohnWebb00 requested changes

2022-04-30 14:39 UTC, JohnWebb00 commented on SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/model/Question.java
> +    private int id;
Remove id variable. Id is assigned on table creation

2022-04-30 14:39 UTC, JohnWebb00 commented on SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/model/Question.java
> +            int id,
Remove id variable. Id is assigned on table creation

2022-04-30 14:39 UTC, JohnWebb00 commented on SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/model/Question.java
> +        this.id = id;
same here

2022-04-30 14:39 UTC, JohnWebb00 commented on SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/model/Question.java
> +    public Question(
Just need this constructor and the empty constructor

2022-04-30 14:39 UTC, JohnWebb00 commented on SmartCarMQTTApp/app/src/main/java/com/example/smartcarmqttapp/model/Question.java
> +    private boolean needsReview;
needsReview is a good edition. will add to my branch as well

2022-04-30 15:00 UTC, JohnWebb00 approved these changes

2022-04-30 15:00 UTC, merged